---
- name: "install python"
  become: yes
  apt:
    name: python
    state: latest
    update_cache: yes

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install npm, nodejs"
  become: yes
  apt:
    name: ["npm", "nodejs"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  apt:
    name: pm2
    global: yes
    production: yes
    state: present