- name: Copy tar file
  template:
    src: /artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Unarchive backend tar file
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: /
    remote_src: no

- name: Executing node
  shell: |
    npm install \
    && pm2 stop default \
    && pm2 start npm -- start