- name: Unarchive backend tar file that is still on local machine
  ansible.builtin.unarchive:
    src: /artifact.tar.gz
    dest: /
    remote_src: no

- name: Executing node
  shell: |
    npm install \
    && pm2 stop default \
    && pm2 start npm -- start